Document: graphite-web
Title: Debian graphite-web Manual
Author: <insert document author here>
Abstract: This manual describes what graphite-web is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/graphite-web/graphite-web.sgml.gz

Format: postscript
Files: /usr/share/doc/graphite-web/graphite-web.ps.gz

Format: text
Files: /usr/share/doc/graphite-web/graphite-web.text.gz

Format: HTML
Index: /usr/share/doc/graphite-web/html/index.html
Files: /usr/share/doc/graphite-web/html/*.html
